<?php

namespace EventBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindAll()
    {
        $query=$this->getEntityManager()->createQuery("SELECT i FROM EventBundle:Reclamation i 
WHERE i.etat=1");
        return $query->getResult();
    }

    public function myfindAll2()
    {
        $query=$this->getEntityManager()->createQuery("SELECT i FROM EventBundle:Reclamation i 
WHERE i.etat=0");
        return $query->getResult();
    }
}
